project_id = "emvolhvffoqsfmhbcadk"

[functions.werewolf-game]
verify_jwt = false

[functions.script-murder]
verify_jwt = false

[functions.truth-dare]
verify_jwt = false

[functions.test-api-connection]
verify_jwt = false
